- name: install our repo
  become: no # need to explicitly do this to allow SSH host key forwarding
  git:
    force: yes
    repo:  "{{ git_repo_url }}"
    dest: "{{ repo_directory }}"
    version: "{{ git_repo_branch }}"
    accept_hostkey: yes

- name: install NGINX webserver
  become: True
  apt:
    name: nginx
    cache_valid_time: "{{ cache_update_valid_secs }}"

- name: install NGINX configuration
  become: True
  template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf

- name: restart nginx
  become: True
  service:
    name: nginx
    state: restarted

- name: install Django and other necessary packages
  become: True
  pip:
    name: [
      'django==3.1.7',
      'pexpect',
      'django-polymorphic',
      'django-rest-framework',
      'django-cors-headers'
    ]

- name: create Django migrations
  django_manage:
    command: makemigrations
    app_path: "{{ django_dir }}"

- name: run Django migrations (bootstrap database)
  django_manage:
    command: migrate
    app_path: "{{ django_dir }}"

- name: check if superuser exists
  shell: echo "from django.contrib.auth import get_user_model; User=get_user_model(); print(User.objects.filter(username='{{django_admin_username}}').count()>0)" | "{{django_dir}}/manage.py" shell
  args:
    chdir: "{{ django_dir }}"
  environment:
    DJANGO_SETTINGS_MODULE: "{{django_settings}}"
  register: superuser_exists

- name: create Django superuser
  django_manage:
    command: "createsuperuser --noinput --username={{django_admin_username}} --email={{django_admin_email}}"
    app_path: "{{ django_dir }}"
  when: superuser_exists.stdout.find('True')==-1

- name: set Django superuser password
  expect:
    command: "{{django_dir}}/manage.py changepassword {{django_admin_username}}"
    responses:
      (?i)Password: "{{django_admin_password}}"
      (?i)again: "{{django_admin_password}}"