#lamp playbooks
- hosts: lamps
  vars:
    cloud_mqtt_broker_port: 50001
  roles:
    - lamp
  module_defaults:
    apt:
      force_apt_get: yes
  pre_tasks:
    - name: Verify Ansible meets our version requirements.
      assert:
        that: "ansible_version.full is version_compare('2.8', '>=')"
        msg: "You must update Ansible to at least 2.8."