- name: enable SSH
  become: yes
  service:
    name: ssh
    enabled: yes
    state: started

- name: make sure wifi power management is disabled
  become: yes
  lineinfile:
    dest: /etc/network/interfaces
    insertafter: iface wlan0 inet manual
    line: '    wireless-power off'