- name: install some dependencies of bleno
  become: True
  tags: bleno
  apt:
    name: libudev-dev
    cache_valid_time: "{{ cache_update_valid_secs }}"

- name: install pybleno via pip
  become: True
  tags: bleno
  pip:
    executable: pip3
    name:
      - pybleno

- name: stop bluetooth daemon
  become: True
  tags: bleno
  systemd:
    name: bluetooth
    state: stopped

- name: disable bluetooth daemon
  become: True
  tags: bleno
  systemd:
    name: bluetooth
    enabled: no

- name: grant python the permissions to use bluetooth without being root
  become: True
  tags: bleno
  shell: setcap cap_net_raw+eip $(eval readlink -f `which python3`)
  args:
    executable: /bin/bash

- name: bring hci0 up (there is also a separate supervisord task to do this at startup)
  become: True
  tags: bleno
  shell: /bin/hciconfig hci0 up