- name: install mosquitto and client tools
  become: yes
  apt:
    name:
      - mosquitto
      - mosquitto-clients

- name: install MQTT bridge configuration
  become: True
  template:
    src: mqtt_bridge.conf
    dest: /etc/mosquitto/conf.d/lamp_bridge.conf

- name: restart mosquitto
  become: True
  service:
    name: mosquitto
    state: restarted

- name: install Paho Python MQTT client library
  become: True
  pip:
    name: paho-mqtt