- name: install the repo
  become: no # need to explicitly do this to allow SSH host key forwarding'
  git:
    force: true
    repo:  "{{ git_repo_url }}"
    dest: "{{ repo_directory }}"
    version: "{{ git_repo_branch }}"
    accept_hostkey: yes